apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: {{ .Values.container.demoImage }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: PostgresOptions__Host
          value: pg-minikube-postgresql.default.svc.cluster.local
        - name: PostgresOptions__Database
          value: usersdb4
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: dbUser
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: dbPassword